import {
  AlertTriangle,
  ArrowRight,
  ArrowRightLeft,
  ArrowUpDown,
  Briefcase,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clipboard,
  Clock,
  Copy,
  ExternalLink,
  Funnel,
  ListChecks,
  Loader2,
  MapPin,
  Minus,
  Moon,
  PanelRight,
  Plane,
  Plus,
  Search,
  ShieldCheck,
  Sun,
  Users,
  X,
  type LucideIcon,
  type LucideProps,
} from "lucide-react"
import { createElement, forwardRef } from "react"

const BrandPlane = forwardRef<SVGSVGElement, LucideProps>(function BrandPlane(
  { color = "currentColor", size = 24, strokeWidth = 2, absoluteStrokeWidth, ...props },
  ref,
) {
  const iconStrokeWidth = absoluteStrokeWidth ? (Number(strokeWidth) * 24) / Number(size) : strokeWidth

  return createElement(
    "svg",
    {
      ...props,
      ref,
      xmlns: "http://www.w3.org/2000/svg",
      width: size,
      height: size,
      viewBox: "0 0 24 24",
      fill: "none",
      stroke: color,
      strokeWidth: iconStrokeWidth,
      strokeLinecap: "round",
      strokeLinejoin: "round",
    },
    createElement("path", { key: "canvas", stroke: "none", d: "M0 0h24v24H0z", fill: "none" }),
    createElement("path", { key: "fold", d: "M10 14l11 -11" }),
    createElement("path", {
      key: "body",
      d: "M21 3l-6.5 18a.55 .55 0 0 1 -1 0l-3.5 -7l-7 -3.5a.55 .55 0 0 1 0 -1l18 -6.5",
    }),
  )
}) as LucideIcon

export const appIconRegistry = {
  alert: AlertTriangle,
  bestValue: ArrowUpDown,
  baggage: Briefcase,
  calendar: Calendar,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  clipboard: Clipboard,
  clock: Clock,
  copy: Copy,
  detail: PanelRight,
  externalLink: ExternalLink,
  filters: Funnel,
  flight: Plane,
  brandPlane: BrandPlane,
  list: ListChecks,
  loading: Loader2,
  location: MapPin,
  migration: ShieldCheck,
  minus: Minus,
  moon: Moon,
  oneWay: ArrowRight,
  passengers: Users,
  plus: Plus,
  roundTrip: ArrowRightLeft,
  search: Search,
  sun: Sun,
  swap: ArrowRightLeft,
  x: X,
} satisfies Record<string, LucideIcon>

export type AppIconName = keyof typeof appIconRegistry
