/**
 * build-css.mjs — Concatenate style layer files → public/app.css
 *
 * Usage:  node scripts/build-css.mjs
 *
 * Layer order:  reset → tokens → base → layout → components → utilities → overrides
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const stylesDir = join(root, 'public', 'styles');
const outFile = join(root, 'public', 'app.css');

/** Ordered source files — order matters for @layer cascade */
const sources = [
  // Foundation
  'tokens.css',
  'themes.css',
  'base.css',
  'layout.css',

  // Components (order within layer doesn't matter, but grouped logically)
  'components/topbar.css',
  'components/theme-switch.css',
  'components/segmented.css',
  'components/field.css',
  'components/icon-button.css',
  'components/badge.css',
  'components/filter-chip.css',
  'components/toolbar-pill.css',
  'components/popover-surface.css',
  'components/panel-header.css',
  'components/card.css',
  'components/detail-panel.css',
  'components/matrix.css',
  'components/results-panel.css',
  'components/empty-state.css',
  'components/skeleton.css',
  'components/toast.css',
  'components/migration.css',

  // Motion (keyframes in components layer)
  'motion.css',

  // Utilities & overrides
  'utilities.css',
  'overrides.css',
];

const LAYER_ORDER = '/* Layer order declaration */\n@layer reset, tokens, base, layout, components, utilities, overrides;\n\n';
const BANNER = `/* ================================================================
   Fly Desk — app.css
   Auto-generated by scripts/build-css.mjs — do not edit directly.
   Edit source files under public/styles/ instead.
   ================================================================ */\n\n`;

let output = BANNER + LAYER_ORDER;

for (const file of sources) {
  const filePath = join(stylesDir, file);
  try {
    const content = readFileSync(filePath, 'utf8');
    output += `/* ── ${file} ── */\n`;
    output += content.trim() + '\n\n';
  } catch (err) {
    console.error(`⚠  Missing: ${file} — skipped`);
  }
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, output, 'utf8');
const lines = output.split('\n').length;
console.log(`✓ Built ${outFile} (${lines} lines, ${(output.length / 1024).toFixed(1)} KB)`);
